"""room model fix

Revision ID: 7d50aebd5c20
Revises: 2db5b4d0398c
Create Date: 2026-04-25 18:06:22.616921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d50aebd5c20'
down_revision: Union[str, Sequence[str], None] = '2db5b4d0398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('length', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('width', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('room_type', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('doors_area', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('windows_area', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'windows_area')
    op.drop_column('rooms', 'doors_area')
    op.drop_column('rooms', 'room_type')
    op.drop_column('rooms', 'height')
    op.drop_column('rooms', 'width')
    op.drop_column('rooms', 'length')
    # ### end Alembic commands ###
